name: deploy-cloud-run

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_REGION:      ${{ secrets.GCP_REGION }}
      GCP_SERVICE:     ${{ secrets.GCP_SERVICE }}
      GCP_WIF_PROVIDER:   ${{ secrets.GCP_WIF_PROVIDER }}
      GCP_SERVICE_ACCOUNT:${{ secrets.GCP_SERVICE_ACCOUNT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.GCP_WIF_PROVIDER }}
          service_account:          ${{ env.GCP_SERVICE_ACCOUNT }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Build & Push image (Artifact Registry)
        run: |
          set -euo pipefail
          DOMAIN="${GCP_REGION}-docker.pkg.dev"
          IMAGE="${DOMAIN}/${GCP_PROJECT_ID}/run-density/${GCP_SERVICE}:${GITHUB_SHA}"
          echo "IMAGE=$IMAGE" >> "$GITHUB_ENV"
          gcloud auth configure-docker "${DOMAIN}" --quiet
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - name: Deploy to Cloud Run
        run: |
          set -euo pipefail
          gcloud run deploy "$GCP_SERVICE" \
            --project "$GCP_PROJECT_ID" \
            --image "$IMAGE" \
            --region "$GCP_REGION" \
            --platform managed \
            --allow-unauthenticated \
            --quiet

      - name: Resolve URL
        id: url
        run: |
          set -euo pipefail
          URL=$(gcloud run services describe "$GCP_SERVICE" --region "$GCP_REGION" --format='value(status.url)')
          echo "BASE_URL=$URL" >> "$GITHUB_ENV"
          echo "Service URL: $URL"

      - name: Health & Ready
        run: |
          set -euo pipefail
          curl -fsS "$BASE_URL/health" | jq -e '.ok==true' >/dev/null
          curl -fsS "$BASE_URL/ready"  | jq -e '.ok==true and .density_loaded and .overlap_loaded' >/dev/null

      - name: Smoke tiny density (retry)
        run: |
          set -euo pipefail
          payload='{
            "paceCsv":"https://raw.githubusercontent.com/thomjeff/run-density/main/data/your_pace_data.csv",
            "overlapsCsv":"https://raw.githubusercontent.com/thomjeff/run-density/main/data/overlaps.csv",
            "startTimes":{"Full":420,"10K":440,"Half":460},
            "segments":[
              {"seg_id":"SMOKE","segment_label":"Start→Friel",
               "eventA":"10K","eventB":"Half",
               "from":0.00,"to":2.70,"direction":"uni","width_m":3.0}
            ],
            "stepKm":0.03,
            "timeWindow":60
          }'

          attempt() {
            echo "Attempt $1:"
            body=$(curl -fsS -X POST "$BASE_URL/api/density" \
                    -H "Content-Type: application/json" -d "$payload") || { echo "$body"; return 1; }
            echo "$body" | jq -e '.engine=="density" and (.segments|length)>=1 and (.segments[0].peak.combined|tonumber) >= 0' >/dev/null \
              && echo "density OK" \
              || { echo "Unexpected response:"; echo "$body" | jq .; return 1; }
          }

          n=0
          until [ $n -ge 5 ]; do
            if attempt $((n+1)); then exit 0; fi
            n=$((n+1)); echo "retrying in 8s…"; sleep 8
          done
          echo "density smoke failed" >&2
          exit 1