name: deploy-cloud-run

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write         # required for Workload Identity Federation
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Enable required APIs (idempotent)
        run: |
          gcloud services enable \
            run.googleapis.com \
            cloudbuild.googleapis.com \
            artifactregistry.googleapis.com \
            iamcredentials.googleapis.com \
            --project "${{ secrets.GCP_PROJECT_ID }}"

      - name: Build & push container (Cloud Build)
        run: |
          gcloud builds submit . \
            --project "${{ secrets.GCP_PROJECT_ID }}" \
            --tag "gcr.io/${{ secrets.GCP_PROJECT_ID }}/run-density:${{ github.sha }}"

      - name: Deploy to Cloud Run (LATEST)
        run: |
          gcloud run deploy run-density \
            --image "gcr.io/${{ secrets.GCP_PROJECT_ID }}/run-density:${{ github.sha }}" \
            --region "${{ secrets.GCP_REGION }}" \
            --allow-unauthenticated \
            --memory=1Gi --cpu=1 \
            --min-instances=0 --max-instances=3 \
            --timeout=300

      - name: Smoke: /health and /ready
        run: |
          set -euo pipefail
          curl -fsSL "${{ secrets.SERVICE_BASE_URL }}/health" | jq .
          curl -fsSL "${{ secrets.SERVICE_BASE_URL }}/ready"  | jq .
