name: smoke-report

on:
  push:
    branches:
      - main
      - feature/**
  workflow_dispatch:

jobs:
  smoke-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Auth with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Resolve URL
        id: resolve
        run: |
          URL=$(gcloud run services describe run-density --platform managed --region ${{ secrets.REGION }} --format='value(status.url)')
          echo "url=$URL" >> $GITHUB_OUTPUT

      - name: Run smoke-report
        run: |
          chmod +x ci/smoke-report.sh
          ./ci/smoke-report.sh "${{ steps.resolve.outputs.url }}"
