name: Validate Data Contracts

# DISABLED: Legacy workflow referencing archived frontend code
# Will be refactored in future milestone
on:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Run validation (cloud env)
        run: |
          RUNFLOW_ENV=cloud python frontend/validation/scripts/validate_data.py
      - name: Run tests
        run: pytest frontend/validation/tests/ -q
      - name: Upload validation report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: validation_report
          path: frontend/validation/output/validation_report.json
